-- AlterTable
ALTER TABLE "Stroke" ALTER COLUMN "color" SET DEFAULT '',
ALTER COLUMN "fontFamily" SET DEFAULT 'Arial',
ALTER COLUMN "fontSize" SET DEFAULT 16,
ALTER COLUMN "h" SET DEFAULT 0,
ALTER COLUMN "radius" SET DEFAULT 0,
ALTER COLUMN "text" SET DEFAULT '',
ALTER COLUMN "w" SET DEFAULT 0;
